name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: git config --global --add safe.directory /__w/losers/losers/ && make clean
    - name: make
      run: git config --global --add safe.directory /__w/losers/losers/ && make
    - name: make wah
      run: git config --global --add safe.directory /__w/losers/losers/ && make wah
    - name: make dist
      run: git config --global --add safe.directory /__w/losers/losers/ && make dist
