name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: switch

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: make clean
    - name: make
      run: make
    - name: make wah
      run: make wah
    - name: make dist
      run: make dist
