name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make dist
      run: export DEVKITPRO=/opt/devkitpro/; git config --global --add safe.directory /__w/losers/losers/ && make dist
