name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
 container: devkitpro/devkita64:latest


    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: chmod +x dkp.sh && ./dkp.sh

    - name: Install dependencies
      run: make module -j66 && make overlay -j66

    - name: Run check
      run: make wah -j66

    - name: Run distcheck
      run: make dist -j66
